server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://dbconn.sealosbja.site:38027/billback?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: qlw9s2gb
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    jdbc-type-for-null: 'null'
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.billback.entity

wechat:
  appid: wxad964e84378db247
  secret: 59523fbf2c7670bec48d5418ff7082b7
jwt:
  secret: your_jwt_secret_key_at_least_32_characters_long
  expiration: 2592000  # 30天，单位秒